### ISSUE TITLE
[Bug] Avalanche Item Page 

### ISSUE THREAD

**Issue by ValorPlayer** [Valor-Inc/Wiki#54]
**Describe the bug**
There is an outdated page! And an Error

**Page with bug**
Avalanche Item Page

**Screenshots**
![image](https://user-images.githubusercontent.com/114792759/193392403-8ce8be26-cf24-46e9-93ef-05fd7bac5f44.png)

**Additional context**
It says it drops from Zol Shard and has 2 weirdly placed asterisks!

**Comment by DeathmodGitHub** [comment]
Thanks big guy, take a well deserved break.
