### ISSUE TITLE
[New]

### ISSUE THREAD

**Issue by VoidEntity420** [Valor-Inc/Wiki#693]
**What do you want to see added to the wiki?**
VoidEntity#7658

T4 phalgomor strat guideline to show the community doing t4 phalgomor with an dedicated party/group

https://docs.google.com/document/d/1mTT2Hnn7VnsAaYEfUpjcbYJNEcZcqXugLbuB0hvXsvU/edit?usp=sharing

**Comment by Rina-Valor** [comment]
done closed
